services:
  - type: web
    name: colegio-naval-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    rootDir: colegio_naval_backend
    envVars:
      - key: DATABASE_URL
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
  - type: static
    name: colegio-naval-frontend
    buildCommand: "echo 'No build command for static site'"
    staticPublishPath: .
    rootDir: .
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"


